### ISSUE TITLE
Add back "All" resource filter button

### ISSUE THREAD

**Issue by arn4v** [covidarmy/frontend#20]
The all tab also serves as a "update check" page where the user can see when the tweets were last updated

If they go directly to a resource and see say in Remdesivir the last tweet came in 50 minutes ago, they would assume it's not updated and leave

**Comment by nilshah98** [comment]
Hi @arn4v ,

I believe fetching all the tweets just for sake of user getting to know that the tweets are updated would be bad design, as fetching all tweets would make the site less performant.
We can think of other alternatives for this - One of which was to actually provide an API which gives the timestamp when the data was last updated in the backend.

Aside from this, there is also the fact that on each click of city, a new page is rendered with the url `covid.army/<city>` . Ideally the earlier version of UI would interpret this as fetching all resources for `<city>` which would put a lot of load on backend as well.

Alternatively, I can implement an `all` button just like other resources, which will go to the url `covid.army/<city>/all` . Although I will then have to intervene in the api call and change the resource specifically when it is `all` since the backend api does not support `all` keyword to fetch all resources. I think this is hacky and not ideal way to do it.

Thoughts ?

**Comment by arn4v** [comment]
@nilshah98 If tweets were fetched in getStaticProps we won't have this issue, I already used this approach in arn4v/covid-twitter where 1000s of tweets were passed as a prop and didn't experience any performance issues.

Also, if we go through with #19, the /city route should be the "all" tab instead of adding a sub /all route. Additionally, The API exists to serve content to frontend and hence I don't see why we can't add an "no filters" route to the backend.

**Comment by nilshah98** [comment]
The use case of fetching all tweets just for the sake of checking whether data is updated, that looks bad design to me. Also, even if there is ISR implemented and less load on the backend, fetching 1000s of tweet statically will still be heavy for the user, and even more tough to scour through. 

I would still think about siding by having an explicit option for fetching all tweets. But fetching all tweets for delhi when I land on `covid.army/delhi` that's bad, imo. 

As far as #19 goes, we surely need an option to look for multiple resources at once. And in this case if a user selects all resources then we can show maximum data.

**Comment by rgxai** [comment]
In my opinion user would need to search for a specific item only. We should focus on increasing the list of items and making them more specific. I don't think an all button would be very useful to a user.
